name: qadam
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  google_nav_bar: ^5.0.6

  cupertino_icons: ^1.0.2
  flutter_signin_button: ^2.0.0
  font_awesome_flutter: ^9.0.0
  percent_indicator: ^4.0.1
  flutter_svg: ^1.1.6
  webview_flutter: ^3.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-Italic.ttf
          style: italic
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-ExtraBold.ttf
          weight: 800
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Medium.ttf
          weight: 500
        - asset: assets/fonts/Comfortaa-Regular.ttf
          weight: 400
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 600

